name: My First CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"

      - name: Check CI/CD
        run: echo "CI/CD is working!"
