name: My First CI
on: 
  push:
    branches:
["main"]

jobs:
  test:
    runs-on:
ubuntu-latest

    steps:
      -name: Say Hello
        run:echo
"hello from github actions"

      -name: check
Runnner
        run: |
        echo "CICD is working "
        whoami
        pwd
        ls
    
